#!/bin/bash
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2011 Vyatta, Inc.
# All Rights Reserved.
#
# Author:       Mohit Mehta <mohit@vyatta.com>
# Description:  Check if the given file is under /config. Used for files that
#               are referenced from the CLI and need to be preserved during
#               image upgrade. Warn the user if these aren't under /config
#
# **** End License ****

FILE=$1
CONFIG_DIR=$2

if [[   ( $FILE =~ ^\/config\/.*$ ) ||					\
        ( $FILE =~ ^\/opt\/vyatta\/etc\/config\/.*$ ) ]]; then
        exit 0
else
        echo Warning: \'$FILE\' lies outside of $CONFIG_DIR directory.	\
             It will not get preserved during image upgrade.
fi
