#!/bin/sh
#
# Module: vyatta-functions
# 
# **** License ****
# Version: VPL 1.0
# 
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Tom Grennan
# Date: 2006
# Description:
# 
# **** End License ****
# 
# 

trap 'progress_indicator "stop"; echo; exit 1' 1
trap 'progress_indicator "stop"; echo; exit 1' 2

# progress indicator for long running programs
progress_indicator () {
  case "$1" in 
    "start") /usr/bin/progress-indicator $2&
             ;;
     "stop") rm -f /tmp/pi.$2
             sleep 2
             echo -n -e "\b"
             ;;
  esac   
}

