#!/bin/sh
#
# Module: vyatta-functions
# 
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Tom Grennan
# Date: 2006
# Description:
# 
# **** End License ****
# 
# 

trap 'progress_indicator "stop"; echo; exit 1' 1
trap 'progress_indicator "stop"; echo; exit 1' 2

# progress indicator for long running programs
progress_indicator () {
  case "$1" in 
    "start") /usr/bin/progress-indicator $2&
             ;;
     "stop") rm -f /tmp/pi.$2
             sleep 2
             echo -n -e "\b"
             ;;
  esac   
}

